name: Compile to WASM and Deploy

on:
  push:
    branches: [main, test-site]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "5.0.3"
          actions-cache-folder: "emsdk-cache"

      - name: Compile to WASM
        run: emcc src/main.cpp -o demo/wasm_module.js -std=c++23 -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]'

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./demo"

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
